"""Verify the vendored OrganSMNIST splits (offline, numpy-only).

This task uses the **official MedMNIST train/val/test splits** as published, and
the official ``.npz`` is **vendored** in ``data/organsmnist.npz`` (checked in),
so the task runs fully offline with no download and no ``medmnist`` package. This
script just verifies that file and its split sizes.

    python prepare_data.py

Provenance
----------
- Dataset : MedMNIST v2 — OrganSMNIST (abdominal CT, sagittal views; 11-class
            organ classification). Homepage: https://medmnist.com
- Splits  : the dataset's OWN official train/val/test (13932 / 2452 / 8827). The
            vendored ``.npz`` is the unmodified official splits; this script
            verifies those full sizes. For speed, ``eval.py`` reads a deterministic
            1/4 slice of train and test at load time (``TRAIN_SUBSAMPLE`` /
            ``TEST_SUBSAMPLE``), so the reported test number is from that slice
            rather than the full official test split.
- File    : ``data/organsmnist.npz`` (override with ``ORGANSMNIST_NPZ``).

Train/val/test discipline
--------------------------
Train your model on ``train``; iterate against ``val`` (``eval.py``); score on
``test`` (``submit.py``, re-runnable). Never train or tune on ``val``/``test``.

DO NOT EDIT this file — the splits and their provenance are frozen.
"""

from __future__ import annotations

import numpy as np

from eval import DATASET, SPLIT_SIZES, data_npz_path  # single source of truth for config


def ensure_data() -> str:
    """Ensure the vendored ``.npz`` is present; return its path.

    The file is checked in, so this is normally a no-op. Safe to call repeatedly.
    """
    npz = data_npz_path()
    if not npz.is_file():
        raise FileNotFoundError(
            f"{npz} not found. The official splits are vendored in data/ — restore "
            f"them from git (or point ORGANSMNIST_NPZ at a copy)."
        )
    return str(npz)


def main() -> None:
    npz = ensure_data()
    print(f"dataset: {DATASET}  (multi-class, 11 organs)")
    print(f"file:    {npz}")
    with np.load(npz) as d:
        for split, expected in SPLIT_SIZES.items():
            n = int(d[f"{split}_images"].shape[0])
            assert n == expected, f"{split}: got {n}, expected {expected}"
            print(f"  {split:<5} {n:>5} samples  (ok)")
    print("\ndata ready — the task runs offline.")


if __name__ == "__main__":
    main()
