"""Held-out test evaluation for the `organsmnist` task.

Score your trained ``model.pt`` on the held-out ``test`` split and check it
against the bar (**test accuracy >= 0.70**). You may run this **as many times as
you like** — keep improving ``model.py``, retrain, and re-submit until you clear
the bar.

    python submit.py --model model.pt

The result is **aggregate-only** (accuracy + AUC over the whole test split): no
per-item test predictions or gold labels are exposed, so you can only see the
single test number, not which individual held-out items you missed. The latest
result is written to ``submission.json`` (the metric-report deliverable); each
run overwrites it and bumps an attempt counter.

Exit code: **0** if the model clears the bar, **1** if it is still below target.

DO NOT EDIT this file.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

from eval import MODEL_FILENAME, TASK_DIR, evaluate, load_model

SUBMISSION_PATH = TASK_DIR / "submission.json"
TARGET_ACC = 0.70  # the held-out test-accuracy bar this task asks you to clear


def _print_summary(record: dict) -> None:
    verdict = "PASS ✅" if record["accuracy"] >= TARGET_ACC else "below target ❌"
    print(f"  accuracy: {record['accuracy']:.4f}   <- primary metric   "
          f"({record['n_correct']}/{record['n']})   target {TARGET_ACC:.2f} -> {verdict}")
    print(f"  AUC:      {record['auc']:.4f}")


def _prev_attempts() -> int:
    if SUBMISSION_PATH.is_file():
        try:
            return int(json.loads(SUBMISSION_PATH.read_text(encoding="utf-8")).get("attempts", 0))
        except (ValueError, OSError):
            return 0
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default=MODEL_FILENAME, help="Path to the TorchScript model.pt.")
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--device", default=None, help="e.g. cuda, cuda:0, cpu (default: auto).")
    args = parser.parse_args()

    model_path = Path(args.model)
    load_model(model_path)  # fail fast with a clear message if the artifact is bad

    result = evaluate(model_path, split="test", batch_size=args.batch_size, device=args.device)
    passed = bool(result["accuracy"] >= TARGET_ACC)

    record = {
        "task": result["task"],
        "split": "test",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "metric": "accuracy",
        "target_accuracy": TARGET_ACC,
        "passed": passed,
        "attempts": _prev_attempts() + 1,
        "model_path": str(model_path.resolve()),
        "model_sha256": hashlib.sha256(model_path.read_bytes()).hexdigest(),
        "n": result["n"],
        "n_correct": result["n_correct"],
        "accuracy": result["accuracy"],
        "auc": result["auc"],
    }
    SUBMISSION_PATH.write_text(json.dumps(record, indent=2, ensure_ascii=False), encoding="utf-8")

    print(f"\nheld-out (test) result — attempt #{record['attempts']}:")
    _print_summary(record)
    print(f"\nsubmission written to {SUBMISSION_PATH}")
    if not passed:
        print("Below the bar — improve model.py, retrain, and run submit.py again.")
    raise SystemExit(0 if passed else 1)


if __name__ == "__main__":
    main()
