"""One-shot held-out evaluation for the `medical_reasoning` task.

Workflow
--------
1. Iterate on your system prompt with ``eval.py`` (the *train* split). It returns
   a rich per-question log so you can see what to fix.
2. When the prompt is final, submit it here **exactly once**. This scores it on
   the held-out ``test.jsonl`` and seals the result.

    python submit.py --prompt-file my_prompt.txt
    python submit.py --prompt "You are a careful diagnostician..."

Why one shot?
-------------
A held-out number is only meaningful if it is measured once. This submitter:

- refuses to run a second time (a sealed ``submission.json`` is the lock), so you
  can't tune against the test set by re-submitting and watching the score, and
- reports **aggregate-only** results (accuracy + per-medical_task breakdown). The
  per-question test reasoning and gold labels are never exposed.

DO NOT EDIT this file, and do not delete ``submission.json`` to get another try —
that voids the held-out guarantee.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

from eval import DEFAULT_WORKERS, TASK_DIR, evaluate

SUBMISSION_PATH = TASK_DIR / "submission.json"


def _read_prompt(args: argparse.Namespace) -> str:
    if args.prompt_file:
        return Path(args.prompt_file).read_text(encoding="utf-8")
    if args.prompt:
        return args.prompt
    if not sys.stdin.isatty():
        return sys.stdin.read()
    raise SystemExit("Provide a prompt via --prompt, --prompt-file, or stdin.")


def _print_summary(record: dict) -> None:
    print(f"  accuracy: {record['accuracy']:.3f}  ({record['n_correct']}/{record['n']})")
    if record.get("n_errors"):
        print(f"  errors:   {record['n_errors']}")
    print("  by medical_task:")
    for task, acc in record["accuracy_by_medical_task"].items():
        print(f"    {task:<24} {acc:.3f}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--prompt", help="System prompt string to submit.")
    parser.add_argument("--prompt-file", help="File containing the system prompt.")
    parser.add_argument("--workers", type=int, default=DEFAULT_WORKERS,
                        help="Parallel requests (does not affect scoring).")
    args = parser.parse_args()

    # Already submitted? Refuse — the held-out set is measured exactly once.
    if SUBMISSION_PATH.is_file():
        prev = json.loads(SUBMISSION_PATH.read_text(encoding="utf-8"))
        print("A prompt has already been submitted for this task — refusing to re-run.")
        print(f"  submitted:     {prev['timestamp']}")
        print(f"  prompt_sha256: {prev['prompt_sha256']}")
        _print_summary(prev)
        print(f"\nThe sealed result is in {SUBMISSION_PATH}.")
        raise SystemExit(1)

    if not os.environ.get("ANTHROPIC_API_KEY"):
        raise SystemExit("Set ANTHROPIC_API_KEY in your environment first.")

    prompt = _read_prompt(args)
    if not prompt or not prompt.strip():
        raise SystemExit("Refusing to submit an empty prompt.")

    result = evaluate(prompt, split="test", workers=args.workers)

    record = {
        "task": "medical_reasoning",
        "split": "test",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "model": result["model"],
        "prompt": prompt,
        "prompt_sha256": hashlib.sha256(prompt.encode("utf-8")).hexdigest(),
        "n": result["n"],
        "n_correct": result["n_correct"],
        "n_errors": result["n_errors"],
        "accuracy": result["accuracy"],
        "accuracy_by_medical_task": result["accuracy_by_medical_task"],
    }
    SUBMISSION_PATH.write_text(
        json.dumps(record, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    print("\nFINAL held-out (test) result — sealed, one-shot:")
    _print_summary(record)
    print(f"\nsubmission written to {SUBMISSION_PATH}")


if __name__ == "__main__":
    main()
