"""Sealed held-out test submissions for the `medical_reasoning_local` task.

The held-out test set (data_test.jsonl, n=100) is scored on EXACTLY TWO
occasions — both are one-shot and both are sealed here:

    python submit.py --baseline               # 1) the shipped baseline_prompt.txt,
                                               #    BEFORE you start iterating
    python submit.py --prompt-file best.txt   # 2) the final prompt your DEV
                                               #    iterations selected, at the end

Selection is by DEV only (run_iter.py); the two test numbers exist purely to
report where the prompt started and where it ended on held-out data.

Why sealed / aggregate-only?
----------------------------
A held-out number is only meaningful if it cannot be tuned against:

- each slot (baseline / final) runs AT MOST ONCE — submission.json is the lock;
  re-running prints the sealed record instead of re-scoring, and
- only aggregate results are reported (accuracy + per-medical_task breakdown).
  The per-question test log, reasoning, and gold labels are never exposed.

DO NOT EDIT this file, and do not delete submission.json to get another try —
that voids the held-out guarantee. (Mirrors medical_reasoning_api/submit.py,
adapted to the local Qwen solver and the two report points.)
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import eval_qwen as E
import results_log as RL

TASK_DIR = Path(__file__).resolve().parent
TEST_DATA = TASK_DIR / "data_test.jsonl"
BASELINE_PROMPT = TASK_DIR / "baseline_prompt.txt"
SUBMISSION_PATH = TASK_DIR / "submission.json"


def _load_submission() -> dict:
    if SUBMISSION_PATH.is_file():
        return json.loads(SUBMISSION_PATH.read_text(encoding="utf-8"))
    return {}


def _print_record(rec: dict) -> None:
    print(f"  slot:     {rec['slot']}   prompt: {rec['prompt_name']}")
    print(f"  accuracy: {rec['accuracy']:.3f}  ({rec['n_correct']}/{rec['n']})")
    if rec.get("n_errors"):
        print(f"  errors:   {rec['n_errors']}")
    print("  by medical_task:")
    for task, acc in sorted(rec.get("accuracy_by_medical_task", {}).items()):
        print(f"    {task:<24} {acc:.3f}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--baseline", action="store_true",
                   help="Score the shipped baseline_prompt.txt on test (once).")
    g.add_argument("--prompt-file", help="The FINAL dev-selected prompt file (once).")
    ap.add_argument("--name", help="Prompt label for the final slot (default: file stem).")
    ap.add_argument("--workers", type=int, default=20)
    args = ap.parse_args()

    if not TEST_DATA.is_file():
        raise SystemExit(f"{TEST_DATA.name} not found.")

    slot = "baseline" if args.baseline else "final"
    submission = _load_submission()
    if slot in submission:
        print(f"REFUSED: the '{slot}' test submission is already sealed "
              f"(submitted {submission[slot]['timestamp']}). The sealed record:")
        _print_record(submission[slot])
        sys.exit(1)

    if args.baseline:
        prompt_path = BASELINE_PROMPT
        name = "baseline"
    else:
        prompt_path = Path(args.prompt_file)
        name = args.name or prompt_path.stem.replace("candidate_prompt_", "").replace("_prompt", "")
    prompt = prompt_path.read_text(encoding="utf-8")

    model = E.detect_model()
    print(f"scoring the held-out test set (n=100) — slot '{slot}', prompt '{name}' …")
    result = E.evaluate(prompt, workers=args.workers, model=model,
                        data_path=TEST_DATA, split="test")

    record = {
        "slot": slot,
        "prompt_name": name,
        "prompt_sha256": hashlib.sha256(prompt.encode("utf-8")).hexdigest(),
        "model": result.get("model"),
        "base_url": result.get("base_url"),
        "n": result["n"],
        "n_correct": result["n_correct"],
        "n_errors": result.get("n_errors", 0),
        "accuracy": result["accuracy"],
        "accuracy_by_medical_task": result.get("accuracy_by_medical_task", {}),
        "timestamp": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        # aggregate-only by design: the per-question test log is never persisted
    }
    submission[slot] = record
    SUBMISSION_PATH.write_text(json.dumps(submission, indent=2, ensure_ascii=False),
                               encoding="utf-8")

    # surface the two report points on the leaderboard/dashboard too
    state = RL.load_state()
    RL.append_run(iteration=max(1, state.get("iteration", 0) or 1), prompt_name=name,
                  split="test", result=result, trigger=f"{slot}_submit")

    print(f"SEALED -> {SUBMISSION_PATH.name}")
    _print_record(record)


if __name__ == "__main__":
    main()
